language: python
python:
  - '2.7'
  - '3.3'
  - 'pypy'
install:
  - pip install -r requirements.txt
script: nosetests
env:
  global:
    # tmdb api key
    - secure: GgD+7/H8oKRtcfkuLDOr1FCH9Wi+vV86ZMuDrwm0CKGlM35YNLRxo5VP7r10eaSeBxgEbR+JFs7J/7cETYK/Aj5tia3ZhaQzYkvIiIRKYmd9TvJQhvet6G9NwFHbfaBPFzpmZ4x6hRN+PdSWNLXaqaUq4h+dSEr9LwXchjVE+g0=
