language: python
python:
  - '2.7'
  - '3.3'
  - 'pypy'
install:
  - pip install -r requirements.txt
script: nosetests
env:
  - secure: bif6CNvtWnkWLiak5bpTJ8mLOgvKU3hqHDMLtcQK8uNuFRHpHY4KRGSCwEIqY/8q9KhGIr8QV9q/Uot/yLPCWnuATLNgUMLitlRPeJ1shG3TIe+1frU2Z/M3FXJbeLS867zDUiVzq33d4V5yNn/MTq9MKpGtz1aoQiKDe2T9aT8=
